# Decap CMS Configuration File

# The backend option specifies how to access the content for your site
backend:
  name: git-gateway
  branch: master # The branch to update (optional; defaults to master)

# Uncomment below to enable drafts https://www.decapcms.org/docs/add-to-your-site/#editorial-workflow
# publish_mode: editorial_workflow

# Uncomment below to enable a link to your published site in the header bar of Decap CMS
# site_url: https://eleventy-netlify-boilerplate.netlify.app/

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Days"
    name: "days"
    files:
      - label: "July 31st"
        name: "july31st"
        file: "days/july31st.md"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Events
            name: events
            widget: list
            fields:
              - {label: Event, name: event, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: Info, name: info, widget: markdown}
      - label: "August 1st"
        name: "august1st"
        file: "days/august1st.md"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Event
            name: event
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: Info, name: info, widget: markdown}
  - label: "Partners"
    name: "partners"
    folder: "partners/partner"
    create: true
    fields:
    - {label: Logo, name: logo, widget: image}
    - {label: Partner, name: partner, widget: string}
    - {label: Website, name: website, widget: string}
    - {label: Blurb, name: blurb, widget: markdown}
  - label: "Speakers"
    name: "speakers"
    folder: "speakers/speaker"
    create: true
    fields:
    - {label: Speaker, name: speaker, widget: string}
    - {label: Company, name: company, widget: string}
    - {label: Title, name: title, widget: string}
    - {label: Main Viewpoint, name: mainviewpoint, widget: string}
    - {label: Dates, name: dates, widget: string}
    - label: "Type"
      name: "type"
      widget: "select"
      multiple: true
      options: ["Moderator", "Panelist"]
    - {label: Bio, name: bio, widget: markdown}
    - {label: Headshot, name: headshot, widget: image}